
from django.contrib import admin
from django.urls import path

from myapp import views

urlpatterns = [
    path('AHome/',views.AHome),
    path('login/',views.login),
    path('login_post/',views.login_post),
    path('changepwd/',views.admin_changepwd),
    path('changepwdPost/',views.admin_changepwd_post),
    path('AddProfile/',views.Addprofile),
    path('Addprofile_post/',views.Addprofile_post),
    path('ViewProfile/',views.ViewProfile),
    path('UpdateProfile/<id>',views.Updateprofile),
    path('Updateprofile_post/', views.Updateprofile_post),
    path('AddProduct/',views.Addproduct),
    path('Addproduct_post/',views.Addproduct_post),
    path('ViewProduct/',views.ViewProduct),
    path('Viewproduct_post/',views.Viewproduct_post),
    path('UpdateProduct/',views.Updateproduct),
    path('Updateproduct_post/',views.Updateproduct_post),
    path('Deleteproduct/<id>',views.Deleteproduct),
    path('AddDBoy/', views.AddDboy),
    path('AddDboy_post/', views.AddDboy_post),
    path('ViewDBoy/', views.ViewDboy),
    path('ViewDboy_post/', views.ViewDboy_post),
    path('UpdateDBoy/<id>',views.UpdateDboy),
    path('UpdateDboy_post/',views.UpdateDboy_post),
    path('DeleteDeliveryboy/<id>',views.DeleteDeliveryboy),

    path('ViewMoreDetails/<id>', views.ViewMoreDetails),
    path('ViewAccRej/',views.ViewARassign),

    path('View_A_R_Assign_post/',views.View_A_R_Assign_post),
    path('AcceptUserOrder/<id>',views.AcceptUserOrder),
    path('RejectUserOrder/<id>',views.RejectUserOrder),
    path('AssignDBoy/<id>',views.AssignDBoy),
    path('AssignDboy_post/',views.AssignDboy_post),
    path('ViewAssignStatus/',views.Viewasssignstatus),
    path('ViewReject/',views.Viewreject),
    path('AddCategory/',views.Addcategory),
    path('Addcategory_post/',views.Addcategory_post),
    path('Deletecategory/<id>',views.Deletecategory),
    path('Editcategory/<id>',views.Editcategory),
    path('Editcategory_post/',views.Editcategory_post),
    path('ViewCategory/',views.Viewcategory),

    path('DBHome/',views.DBHome),
    path('ViewDBoyProfile/',views.ViewDboyprofile),
    path('EditDBoyProfile/',views.EditDboyprofile),
    path('EditDboyprofile_post/',views.EditDboyprofile_post),
    path('ViewAssign/', views.Viewassign),
    path('UpdateOrderStatus/',views.UpdateOrderstatus),
    path('UpdateOrderstatus_post/',views.UpdateOrderstatus_post),
    path('DBoyChangepwd/',views.DBoy_Changepwd),
    path('DBoy_Changepwd_post/',views.DBoy_Changepwd_post),

    path('UserHome/', views.UserHome),
    path('Regiser/',views.Register),
    path('Register_post/',views.Register_post),
    path('ViewRegister/',views.Viewregister),
    path('UpdateRegiser/<id>',views.Updateregister),
    path('Updateregister_post/',views.Updateregister_post),
    path('UserViewProduct/',views.User_Viewproduct),
    path('User_Viewproduct_post/',views.User_Viewproduct_post),
    # path('OrderProduct/', views.Orderproduct),
    # path('Orderproduct_post/', views.Orderproduct_post),
    path('Vieworder/',views.Vieworder),
    path('Vieworder_post/',views.Vieworder_post),
    path('ViewDeliveryStatus/',views.ViewDeliverystatus),
    path('UserChangepwd/',views.User_Changepwd),
    path('User_Changepwd_post/',views.User_Changepwd_post),
    path('UserViewCatgory/',views.User_Viewcategory),
    path('User_Addtocart/<id>',views.User_Addtocart),
    path('User_Addtocart_post/',views.User_Addtocart_post),
    path('User_ViewCart/',views.User_ViewCart),
    path('User_Buynow/',views.User_Buynow),
    path('User_directbuy/<id>',views.User_directbuy),
    path('User_directbuy_post/',views.User_directbuy_post),

]